apiVersion: apps/v1
kind: Deployment
metadata:
  name: give-flower
  labels:
    app: give-flower
spec:
  replicas: 1
  selector:
    matchLabels:
      app: give-flower
  template:
    metadata:
      labels:
        app: give-flower
    spec:
      nodeSelector:
        master: "true"
      containers:
        - name: give-flower
          image: zhoudian64/give-flower:v1.03
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: give-flower-svc
spec:
  selector:
    app: give-flower
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80