apiVersion: apps/v1
kind: Deployment
metadata:
  name: nicolas-webdis
spec:
  selector:
    matchLabels:
      run: nicolas-webdis
  replicas: 1
  template:
    metadata:
      labels:
        run: nicolas-webdis
    spec:
      containers:
        - name: nicolas-webdis
          image: nicolas/webdis
          ports:
            - containerPort: 7379
---
apiVersion: v1
kind: Service
metadata:
  name: nicolas-webdis-svc
spec:
  selector:
    run: nicolas-webdis
  ports:
    - protocol: TCP
      port: 7379
      targetPort: 7379